# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoodwatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=140)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HoodwatchMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoodwatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hoodwatch.Hoodwatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hoodwatchs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hoodwatch',
            name='occupants',
            field=models.ManyToManyField(through='hoodwatch.HoodwatchMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hoodwatchmember',
            unique_together=set([('hoodwatch', 'user')]),
        ),
    ]
